require 'mercadopago/endpoint/base'
require 'mercadopago/endpoint/payment_methods'
require 'mercadopago/endpoint/payment'
require 'mercadopago/endpoint/preference'
require 'mercadopago/endpoint/card_token'
